const MAIN_COLOR = '#124559';
const MAIN_FONT_COLOR = '#01161E';
const SECONDARY_COLOR = '#AEC3B0';
const SECONDARY_FONT_COLOR = '#598392';
const BRIGHT_COLOR = '#EFF6E0';

module.exports = {
    MAIN_COLOR,
    MAIN_FONT_COLOR,
    SECONDARY_COLOR,
    SECONDARY_FONT_COLOR,
    BRIGHT_COLOR
}