const SECONDARY_COLOR = '#124559';
const MAIN_FONT_COLOR = '#01161E';
const MAIN_COLOR = '#AEC3B0';
const SECONDARY_FONT_COLOR = '#598392';
const ACCENT_COLOR = '#dee7df ';

export {
    SECONDARY_COLOR,
    MAIN_FONT_COLOR,
    MAIN_COLOR,
    SECONDARY_FONT_COLOR,
    ACCENT_COLOR
}