const MAIN_COLOR = '#124559';
const MAIN_FONT_COLOR = '#01161E';
const SECONDARY_COLOR = '#AEC3B0';
const SECONDARY_FONT_COLOR = '#598392';
const BRIGHT_COLOR = '#dee7df ';

export {
    MAIN_COLOR,
    MAIN_FONT_COLOR,
    SECONDARY_COLOR,
    SECONDARY_FONT_COLOR,
    BRIGHT_COLOR
}